var binary = require('node-pre-gyp');
var path = require('path');
var binding_path = binary.find(path.resolve(path.join(__dirname,'./package.json')));
var binding = require(binding_path);
binding.SEQTYPE_UNKNOWN = 0;
binding.SEQTYPE_PROTEIN = 1;
binding.SEQTYPE_RNA = 2;
binding.SEQTYPE_DNA = 3;
module.exports = binding;